### ISSUE TITLE
小程序上搜 TZVideo 未找到

### ISSUE THREAD

**Issue by xoyabc** [lovemefan/TZVideo#1]
如题

**Comment by lovemefan** [comment]
由于个人小程序的限制无法上线，目前是我个人和亲人和朋友在使用，感谢关注和提问。这个项目还会继续完善的。

**Comment by xoyabc** [comment]
感谢回复，期待能早日使用上。

**Comment by liutangyuan** [comment]
> 由于个人小程序的限制无法上线，目前是我个人和亲人和朋友在使用，感谢关注和提问。这个项目还会继续完善的。

大佬，能加个微信交流一下吗，我尝试改了下云开发版，但后端有些地方我也想学习一下~ 我的VX：qianustb

**Comment by zhzhh2019** [comment]
纯js得，没有后端
