### ISSUE TITLE
作者是后端没更新吗？？跑起来后访问/api-okzy报404

### ISSUE THREAD

**Issue by engineMomo** [lovemefan/TZVideo#2]

**Comment by lovemefan** [comment]
你好，因为太忙后端停更了好长一段时间了😂，现在豆瓣接口也因为更新失效了，需要重新抓包处理了。api-okzy 用的是http://cj.bajiecaiji.com/inc/feifei3bjm3u8/index.php

**Comment by lovemefan** [comment]
closed
